<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MassTransit.Abstractions" Version="8.5.7" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fiap.CloudGames.Domain\Fiap.CloudGames.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Payments\Commands\" />
  </ItemGroup>

</Project>
